/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `midterm` - Midterm
* `final` - Final Exam
* `homework` - Homework
* `project` - Project
* `quiz` - Quiz
* `attendance` - Attendance
* `other` - Other
 */
export type AssessmentTypeEnum = typeof AssessmentTypeEnum[keyof typeof AssessmentTypeEnum];


export const AssessmentTypeEnum = {
  midterm: 'midterm',
  final: 'final',
  homework: 'homework',
  project: 'project',
  quiz: 'quiz',
  attendance: 'attendance',
  other: 'other',
} as const;
