/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type CoreFileImportUploadCreateBodyImportType = typeof CoreFileImportUploadCreateBodyImportType[keyof typeof CoreFileImportUploadCreateBodyImportType];


export const CoreFileImportUploadCreateBodyImportType = {
  auto: 'auto',
  students: 'students',
  courses: 'courses',
  assessments: 'assessments',
  grades: 'grades',
  learning_outcomes: 'learning_outcomes',
  program_outcomes: 'program_outcomes',
} as const;
