/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `guest` - Guest
* `student` - Student
* `instructor` - Instructor
* `admin` - Admin
 */
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];


export const RoleEnum = {
  guest: 'guest',
  student: 'student',
  instructor: 'instructor',
  admin: 'admin',
} as const;
