/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentLearningOutcomeMapping } from './assessmentLearningOutcomeMapping';

export interface Assessment {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  readonly course: string;
  date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  total_score?: number;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight: number;
  readonly lo_mappings: readonly AssessmentLearningOutcomeMapping[];
  readonly created_at: string;
}
