/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentTypeEnum } from './assessmentTypeEnum';

/**
 * For creating/updating assessments
 */
export interface AssessmentCreate {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  course: number;
  date: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  total_score?: number;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight: number;
  assessment_type?: AssessmentTypeEnum;
}
