/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentTypeEnum } from './assessmentTypeEnum';
import type { AssessmentLearningOutcomeMapping } from './assessmentLearningOutcomeMapping';

export interface Assessment {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  assessment_type?: AssessmentTypeEnum;
  /** Single-sentence description of what this assessment evaluates, used for AI weight correlation */
  description?: string;
  readonly course: string;
  date?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  total_score?: number;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
  readonly lo_mappings: readonly AssessmentLearningOutcomeMapping[];
  readonly created_at: string;
}
