/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Single item in a bulk sync request.
 */
export interface BulkAssessmentLOMappingItem {
  temp_id?: number;
  id?: number;
  assessment_id?: number;
  learning_outcome_id?: number;
  weight?: number;
}
