/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { BulkLOPOMappingItem } from './bulkLOPOMappingItem';

/**
 * Bulk sync payload for LO-PO mappings.
 */
export interface BulkLOPOMapping {
  course_id: number;
  creates?: BulkLOPOMappingItem[];
  updates?: BulkLOPOMappingItem[];
  deletes?: number[];
}
