/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { BulkAssessmentLOMappingItem } from './bulkAssessmentLOMappingItem';

/**
 * Bulk sync payload for assessment-LO mappings.
 */
export interface BulkAssessmentLOMapping {
  course_id: number;
  creates?: BulkAssessmentLOMappingItem[];
  updates?: BulkAssessmentLOMappingItem[];
  deletes?: number[];
}
