/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Single permission item in a bulk permission update request.
 */
export interface BulkPermissionItem {
  resource_area: string;
  permission_tier: string;
}
