/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Single permission update item with ID for bulk partial updates.
 */
export interface BulkPermissionUpdateItem {
  id: number;
  permission_tier?: string;
  resource_area?: string;
}
