/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { BulkAssessmentDescriptionUpdateAssessmentsItem } from './bulkAssessmentDescriptionUpdateAssessmentsItem';

/**
 * Bulk update assessment descriptions.

Request body:
    {
        "assessments": [
            {"id": 1, "description": "Vize sınavı: ..."},
            {"id": 2, "description": "Final sınavı: ..."},
        ]
    }
 */
export interface BulkAssessmentDescriptionUpdate {
  /** @minItems 1 */
  assessments: BulkAssessmentDescriptionUpdateAssessmentsItem[];
}
