/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportLearningOutcomesUploadRetrieve400Checks } from './coreFileImportLearningOutcomesUploadRetrieve400Checks';
import type { CoreFileImportLearningOutcomesUploadRetrieve400Details } from './coreFileImportLearningOutcomesUploadRetrieve400Details';

export type CoreFileImportLearningOutcomesUploadRetrieve400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: CoreFileImportLearningOutcomesUploadRetrieve400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: CoreFileImportLearningOutcomesUploadRetrieve400Details;
};
