/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Course } from './course';

/**
 * Renamed to avoid conflicts with evaluation app
 */
export interface CoreLearningOutcome {
  readonly id: number;
  /** @maxLength 10 */
  code: string;
  description: string;
  readonly course: Course;
  readonly created_at: string;
}
