/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramTemplatesUploadRetrieve400Checks } from './coreFileImportProgramTemplatesUploadRetrieve400Checks';
import type { CoreFileImportProgramTemplatesUploadRetrieve400Details } from './coreFileImportProgramTemplatesUploadRetrieve400Details';

export type CoreFileImportProgramTemplatesUploadRetrieve400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: CoreFileImportProgramTemplatesUploadRetrieve400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: CoreFileImportProgramTemplatesUploadRetrieve400Details;
};
