/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramOutcomesUploadCreate200Created } from './coreFileImportProgramOutcomesUploadCreate200Created';
import type { CoreFileImportProgramOutcomesUploadCreate200Updated } from './coreFileImportProgramOutcomesUploadCreate200Updated';

export type CoreFileImportProgramOutcomesUploadCreate200 = {
  created?: CoreFileImportProgramOutcomesUploadCreate200Created;
  updated?: CoreFileImportProgramOutcomesUploadCreate200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
