/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportLearningOutcomesUploadCreate200Created } from './coreFileImportLearningOutcomesUploadCreate200Created';
import type { CoreFileImportLearningOutcomesUploadCreate200Updated } from './coreFileImportLearningOutcomesUploadCreate200Updated';

export type CoreFileImportLearningOutcomesUploadCreate200 = {
  created?: CoreFileImportLearningOutcomesUploadCreate200Created;
  updated?: CoreFileImportLearningOutcomesUploadCreate200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
