/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportAssignmentScoresValidateCreate200Checks } from './coreFileImportAssignmentScoresValidateCreate200Checks';

export type CoreFileImportAssignmentScoresValidateCreate200 = {
  is_valid?: boolean;
  phase_reached?: string;
  checks?: CoreFileImportAssignmentScoresValidateCreate200Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
};
