/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramTemplatesUploadRetrieve200Created } from './coreFileImportProgramTemplatesUploadRetrieve200Created';
import type { CoreFileImportProgramTemplatesUploadRetrieve200Updated } from './coreFileImportProgramTemplatesUploadRetrieve200Updated';

export type CoreFileImportProgramTemplatesUploadRetrieve200 = {
  created?: CoreFileImportProgramTemplatesUploadRetrieve200Created;
  updated?: CoreFileImportProgramTemplatesUploadRetrieve200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
