/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramOutcomesUploadRetrieve200Created } from './coreFileImportProgramOutcomesUploadRetrieve200Created';
import type { CoreFileImportProgramOutcomesUploadRetrieve200Updated } from './coreFileImportProgramOutcomesUploadRetrieve200Updated';

export type CoreFileImportProgramOutcomesUploadRetrieve200 = {
  created?: CoreFileImportProgramOutcomesUploadRetrieve200Created;
  updated?: CoreFileImportProgramOutcomesUploadRetrieve200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
