/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramTemplatesUploadCreate400Checks } from './coreFileImportProgramTemplatesUploadCreate400Checks';
import type { CoreFileImportProgramTemplatesUploadCreate400Details } from './coreFileImportProgramTemplatesUploadCreate400Details';

export type CoreFileImportProgramTemplatesUploadCreate400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: CoreFileImportProgramTemplatesUploadCreate400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: CoreFileImportProgramTemplatesUploadCreate400Details;
};
