/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramOutcomesUploadRetrieve400Checks } from './coreFileImportProgramOutcomesUploadRetrieve400Checks';
import type { CoreFileImportProgramOutcomesUploadRetrieve400Details } from './coreFileImportProgramOutcomesUploadRetrieve400Details';

export type CoreFileImportProgramOutcomesUploadRetrieve400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: CoreFileImportProgramOutcomesUploadRetrieve400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: CoreFileImportProgramOutcomesUploadRetrieve400Details;
};
