/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportLearningOutcomesUploadRetrieve200Created } from './coreFileImportLearningOutcomesUploadRetrieve200Created';
import type { CoreFileImportLearningOutcomesUploadRetrieve200Updated } from './coreFileImportLearningOutcomesUploadRetrieve200Updated';

export type CoreFileImportLearningOutcomesUploadRetrieve200 = {
  created?: CoreFileImportLearningOutcomesUploadRetrieve200Created;
  updated?: CoreFileImportLearningOutcomesUploadRetrieve200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
