/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramTemplatesUploadCreate200Created } from './coreFileImportProgramTemplatesUploadCreate200Created';
import type { CoreFileImportProgramTemplatesUploadCreate200Updated } from './coreFileImportProgramTemplatesUploadCreate200Updated';

export type CoreFileImportProgramTemplatesUploadCreate200 = {
  created?: CoreFileImportProgramTemplatesUploadCreate200Created;
  updated?: CoreFileImportProgramTemplatesUploadCreate200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
