/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type CoreCoursesListParams = {
/**
 * Filter courses by department ID
 */
department?: number;
/**
 * Filter courses by instructor ID
 */
instructor?: number;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Filter courses by term ID
 */
term?: number;
};
