/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportLearningOutcomesUploadCreate400Checks } from './coreFileImportLearningOutcomesUploadCreate400Checks';
import type { CoreFileImportLearningOutcomesUploadCreate400Details } from './coreFileImportLearningOutcomesUploadCreate400Details';

export type CoreFileImportLearningOutcomesUploadCreate400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: CoreFileImportLearningOutcomesUploadCreate400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: CoreFileImportLearningOutcomesUploadCreate400Details;
};
