/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreFileImportProgramOutcomesUploadCreate400Checks } from './coreFileImportProgramOutcomesUploadCreate400Checks';
import type { CoreFileImportProgramOutcomesUploadCreate400Details } from './coreFileImportProgramOutcomesUploadCreate400Details';

export type CoreFileImportProgramOutcomesUploadCreate400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: CoreFileImportProgramOutcomesUploadCreate400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: CoreFileImportProgramOutcomesUploadCreate400Details;
};
