/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for CourseTemplateAssessmentLOMapping.
 */
export interface CourseTemplateAssessmentLOMapping {
  readonly id: number;
  template_assessment: number;
  template_learning_outcome: number;
  /**
   * 0 to 5
   * @minimum 0
   * @maximum 5
   */
  weight: number;
}
