/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Program } from './program';
import type { Term } from './term';
import type { CourseInstructorsItem } from './courseInstructorsItem';

export interface Course {
  readonly id: number;
  /** @maxLength 10 */
  code: string;
  /** @maxLength 255 */
  name: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  credits?: number;
  readonly program: Program;
  readonly term: Term;
  /** Get instructor details including name, surname, and title. */
  readonly instructors: readonly CourseInstructorsItem[];
  readonly created_at: string;
}
