/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Program } from './program';

/**
 * Serializer for CourseTemplate model.

Provides bidirectional serialization with nested read representation
and flat write representation for the program FK.
 */
export interface CourseTemplate {
  readonly id: number;
  /** @maxLength 10 */
  code: string;
  /** @maxLength 255 */
  name: string;
  /**
   * @minimum 0
   * @maximum 2147483647
   */
  credits?: number;
  readonly program: Program;
  program_id: number;
  /** Return the number of Courses instantiated from this template. */
  readonly instance_count: number;
  readonly created_at: string;
  readonly updated_at: string;
}
