/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Course } from './course';

export interface CourseEnrollment {
  readonly id: number;
  readonly student: string;
  readonly course: Course;
  readonly enrolled_at: string;
}
