/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Program } from './program';
import type { Term } from './term';
import type { CourseInstructorsItem } from './courseInstructorsItem';

/**
 * Serializer for Course model.

Handles bidirectional serialization with nested read representation
and flat write representation.

Fields:
    id: Course ID
    code: Course code (e.g., "CS101")
    name: Course name
    credits: Credit hours
    program: Nested program object (read-only)
    term: Nested term object (read-only)
    program_id: Program ID for writes (write-only)
    term_id: Term ID for writes (write-only)
    instructors: List of instructor details (read-only)
    created_at: Creation timestamp
 */
export interface Course {
  readonly id: number;
  /** @maxLength 10 */
  code: string;
  /** @maxLength 255 */
  name: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  credits?: number;
  readonly program: Program;
  readonly term: Term;
  program_id: number;
  term_id: number;
  /** Get instructor details including name and title.

Args:
    obj: Course instance being serialized

Returns:
    List of dictionaries containing instructor details:
        - id: User ID
        - first_name: Instructor's first name
        - last_name: Instructor's last name
        - title: Academic title (if available) */
  readonly instructors: readonly CourseInstructorsItem[];
  readonly created_at: string;
}
