/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { RoleEnum } from './roleEnum';

/**
 * Full user serializer with all fields.
 */
export interface CustomUser {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
  role?: RoleEnum;
  readonly department: string;
  /** @nullable */
  department_id?: number | null;
  readonly university: string;
  /** @nullable */
  university_id?: number | null;
  /** Designates whether this user should be treated as active. Unselect this instead of deleting accounts. */
  is_active?: boolean;
  /** Designates whether the user can log into this admin site. */
  is_staff?: boolean;
  readonly date_joined: string;
}
