/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Learning Outcome serializer for evaluation app to avoid conflicts
 */
export interface EvaluationLearningOutcome {
  readonly id: number;
  /** @maxLength 10 */
  code: string;
  description: string;
  readonly course: string;
  readonly created_at: string;
}
