/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type EvaluationGradesListParams = {
/**
 * Filter grades by assessment ID
 */
assessment?: number;
/**
 * Filter grades by course ID
 */
course?: number;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Filter grades by student ID
 */
student?: number;
};
