/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { FileValidationResponseFileInfo } from './fileValidationResponseFileInfo';

export interface FileValidationResponse {
  message: string;
  available_sheets: string[];
  file_info: FileValidationResponseFileInfo;
}
