/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type FileValidationResponseFileInfo = {[key: string]: unknown};
