/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { FileImportResponseResults } from './fileImportResponseResults';

/**
 * Serializer for file import operation responses.

Fields:
    message: Human-readable status message
    results: Dictionary containing import statistics (created, updated, errors)
 */
export interface FileImportResponse {
  message: string;
  results: FileImportResponseResults;
}
