/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { ResourceAreaEnum } from './resourceAreaEnum';
import type { PermissionTierEnum } from './permissionTierEnum';

export interface InstructorPermission {
  readonly id: number;
  readonly instructor: string;
  instructor_id: number;
  readonly department_head: string;
  department_head_id: number;
  resource_area: ResourceAreaEnum;
  readonly resource_area_display: string;
  permission_tier?: PermissionTierEnum;
  readonly permission_tier_display: string;
}
