/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for instantiating a course from a template.
 */
export interface InstantiateCourseTemplate {
  term_id: number;
}
