/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface InstructorProfile {
  readonly id: number;
  readonly user: User;
  user_id: number;
  /** @maxLength 100 */
  title?: string;
}
