/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `running` - running
* `success` - success
* `failed` - failed
 */
export type JobProgressEventStatusEnum = typeof JobProgressEventStatusEnum[keyof typeof JobProgressEventStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobProgressEventStatusEnum = {
  running: 'running',
  success: 'success',
  failed: 'failed',
} as const;
