/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { TypeEnum } from './typeEnum';
import type { JobProgressEventStatusEnum } from './jobProgressEventStatusEnum';

/**
 * SSE event payload for job progress and completion events.
 */
export interface JobProgressEvent {
  /** Event type

* `progress` - progress
* `complete` - complete */
  type: TypeEnum;
  /** ID of the job this event relates to */
  job_id: number;
  /** Current job status

* `running` - running
* `success` - success
* `failed` - failed */
  status: JobProgressEventStatusEnum;
  /** Current progress step (progress events) */
  current?: number;
  /** Total steps (progress events) */
  total?: number;
  /** Items created so far (progress events) */
  created?: number;
  /** Total courses created (complete events) */
  courses_created?: number;
  /** Total templates processed (complete events) */
  total_templates?: number;
  /** Error message if status is failed */
  error?: string;
}
