/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { LearningOutcomeProgramOutcomeMapping } from './learningOutcomeProgramOutcomeMapping';

export interface PaginatedLearningOutcomeProgramOutcomeMappingList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: LearningOutcomeProgramOutcomeMapping[];
}
