/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for CourseTemplateLOPOMapping.
 */
export interface PatchedCourseTemplateLOPOMapping {
  readonly id?: number;
  template_learning_outcome?: number;
  /** @nullable */
  program_outcome?: number | null;
  /** @nullable */
  program_outcome_template?: number | null;
  /**
   * 0 to 5
   * @minimum 0
   * @maximum 5
   */
  weight?: number;
}
