/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for DegreeLevel model.

Fields:
    id: Degree level ID
    name: Degree name (e.g., "Bachelor of Science")
    level: Numeric level for ordering
 */
export interface PatchedDegreeLevel {
  readonly id?: number;
  /** @maxLength 100 */
  name?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  level?: number;
}
