/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { BulkPermissionUpdateItem } from './bulkPermissionUpdateItem';

/**
 * Bulk partial update payload for instructor permissions - sends only changed items.
 */
export interface PatchedBulkPermissionUpdate {
  updates?: BulkPermissionUpdateItem[];
}
