/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface PatchedProgramHeadProfile {
  readonly id?: number;
  readonly user?: User;
  user_id?: number;
  readonly program?: string;
  program_id?: number;
  readonly created_at?: string;
}
