/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for ProgramOutcome model.

Handles serialization of program outcomes. Program and term are read-only
as they are typically set during creation and shouldn't change.

Fields:
    id: Outcome ID
    code: Outcome code (e.g., "PO1")
    description: Detailed description
    program: Program ID (read-only)
    term: Term ID (read-only)
    weight: Relative weight (0.0 to 1.0)
    created_at: Creation timestamp
 */
export interface PatchedProgramOutcome {
  readonly id?: number;
  /** @maxLength 10 */
  code?: string;
  description?: string;
  readonly program?: number;
  readonly term?: number;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
  readonly created_at?: string;
}
