/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreLearningOutcome } from './coreLearningOutcome';
import type { ProgramOutcome } from './programOutcome';

/**
 * Serializer for LearningOutcomeProgramOutcomeMapping model.

Handles bidirectional serialization of LO-PO mappings with nested
read representation and ID-based write representation.

Uses LearningOutcomeProgramOutcomeMappingListSerializer for validation
when processing multiple mappings.

Fields:
    id: Mapping ID
    course: Course ID
    learning_outcome: Nested LO object (read-only)
    learning_outcome_id: LO ID for writes (write-only)
    program_outcome: Nested PO object (read-only)
    program_outcome_id: PO ID for writes (write-only)
    weight: Mapping weight (0.0 to 1.0)
 */
export interface PatchedLearningOutcomeProgramOutcomeMapping {
  readonly id?: number;
  course?: number;
  readonly learning_outcome?: CoreLearningOutcome;
  learning_outcome_id?: number;
  readonly program_outcome?: ProgramOutcome;
  program_outcome_id?: number;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
}
