/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Program } from './program';

/**
 * Serializer for reusable program outcome templates.
 */
export interface PatchedProgramOutcomeTemplate {
  readonly id?: number;
  /** @maxLength 10 */
  code?: string;
  description?: string;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
  readonly program?: Program;
  program_id?: number;
  readonly instance_count?: number;
  readonly created_at?: string;
  readonly updated_at?: string;
}
