/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Course } from './course';

/**
 * Serializer for LearningOutcome model (core app version).

Renamed to avoid conflicts with evaluation app's LearningOutcomeSerializer.
Includes nested course details for read operations.

Fields:
    id: Learning outcome ID
    code: Outcome code (e.g., "LO1")
    description: Detailed description
    course: Nested course object (read-only)
    created_at: Creation timestamp
 */
export interface PatchedCoreLearningOutcome {
  readonly id?: number;
  /** @maxLength 10 */
  code?: string;
  description?: string;
  readonly course?: Course;
  readonly created_at?: string;
}
