/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreLearningOutcome } from './coreLearningOutcome';
import type { ProgramOutcome } from './programOutcome';

export interface PatchedLearningOutcomeProgramOutcomeMapping {
  readonly id?: number;
  course?: number;
  readonly learning_outcome?: CoreLearningOutcome;
  readonly program_outcome?: ProgramOutcome;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
}
