/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * For creating/updating grades
 */
export interface PatchedStudentGradeCreate {
  readonly id?: number;
  student?: number;
  assessment?: number;
  /** @minimum 0 */
  score?: number;
}
