/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { SemesterEnum } from './semesterEnum';

/**
 * Serializer for Term (academic semester) model.

Fields:
    id: Term ID
    name: Term name (e.g., "Fall 2025")
    is_active: Whether this is the currently active term
 */
export interface PatchedTerm {
  readonly id?: number;
  /**
   * e.g., Fall 2025
   * @maxLength 100
   */
  name?: string;
  is_active?: boolean;
  /**
   * The calendar year the academic year starts (e.g., 2024 for AY 2024-2025)
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   * @nullable
   */
  academic_year?: number | null;
  semester?: SemesterEnum;
}
