/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { EvaluationLearningOutcome } from './evaluationLearningOutcome';

/**
 * Nested inside AssessmentSerializer
 */
export interface PatchedAssessmentLearningOutcomeMapping {
  readonly id?: number;
  readonly learning_outcome?: EvaluationLearningOutcome;
  learning_outcome_id?: number;
  /**
   * 0.0 to 1.0
   * @minimum 0
   * @maximum 1
   */
  weight?: number;
}
