/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for Department model.

Handles serialization of department data including university reference.

Fields:
    id: Department ID
    name: Department name
    code: Department code
    university: Related university ID
 */
export interface PatchedDepartment {
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
  /** @maxLength 10 */
  code?: string;
  university?: number;
}
