/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Department } from './department';
import type { DegreeLevel } from './degreeLevel';

export interface PatchedProgram {
  readonly id?: number;
  /** @maxLength 255 */
  name?: string;
  /** @maxLength 10 */
  code?: string;
  readonly department?: Department;
  readonly degree_level?: DegreeLevel;
}
