/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedProgramOutcome {
  readonly id?: number;
  /** @maxLength 10 */
  code?: string;
  description?: string;
  readonly department?: string;
  readonly term?: string;
  readonly created_at?: string;
}
