/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { ProgramStat } from './programStat';
import type { EnrollmentTrend } from './enrollmentTrend';

export interface ProgramStatsResponse {
  programs: ProgramStat[];
  enrollment_trends: EnrollmentTrend[];
}
