/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { GpaByYear } from './gpaByYear';
import type { ProgramStat } from './programStat';
import type { YearLevelBreakdown } from './yearLevelBreakdown';

export interface ProgramStatsResponse {
  programs: ProgramStat[];
  year_level_breakdown: YearLevelBreakdown[];
  gpa_by_year: GpaByYear[];
}
