/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export interface ProgramStat {
  id: number;
  code: string;
  name: string;
  total_students: number;
  total_faculty: number;
  /** @nullable */
  avg_score: number | null;
  lo_count: number;
  po_count: number;
}
