/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for Program model.

Fields:
    id: Program ID
    name: Program name
    code: Program code
    department: Department ID
    degree_level: Degree level ID
 */
export interface Program {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  /** @maxLength 10 */
  code: string;
  department: number;
  degree_level: number;
}
