/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `courses` - Courses
* `programs` - Programs
* `learning_outcomes` - Learning Outcomes
* `program_outcomes` - Program Outcomes
* `students` - Students
* `lo_po_weights` - LO-PO Weights
* `assessment_lo_weights` - Assessment-LO Weights
* `assessments` - Assessments
 */
export type ResourceAreaEnum = typeof ResourceAreaEnum[keyof typeof ResourceAreaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceAreaEnum = {
  courses: 'courses',
  programs: 'programs',
  learning_outcomes: 'learning_outcomes',
  program_outcomes: 'program_outcomes',
  students: 'students',
  lo_po_weights: 'lo_po_weights',
  assessment_lo_weights: 'assessment_lo_weights',
  assessments: 'assessments',
} as const;
