/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `guest` - Guest
* `student` - Student
* `instructor` - Instructor
* `department_head` - Department Head
* `admin` - Admin
 */
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleEnum = {
  guest: 'guest',
  student: 'student',
  instructor: 'instructor',
  department_head: 'department_head',
  admin: 'admin',
} as const;
