/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { TaskTypeEnum } from './taskTypeEnum';
import type { StatusEnum } from './statusEnum';

export interface ScoreRecomputeJob {
  readonly id: number;
  task_type?: TaskTypeEnum;
  status?: StatusEnum;
  /** @nullable */
  course?: number | null;
  /** @nullable */
  triggered_by?: number | null;
  /** @maxLength 255 */
  celery_task_id?: string;
  readonly created_at: string;
  readonly updated_at: string;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  finished_at?: string | null;
  error?: string;
}
