/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `fall` - Güz
* `spring` - Bahar
* `summer` - Yaz
 */
export type SemesterEnum = typeof SemesterEnum[keyof typeof SemesterEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SemesterEnum = {
  fall: 'fall',
  spring: 'spring',
  summer: 'summer',
} as const;
