/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `pending` - Pending
* `running` - Running
* `success` - Success
* `failed` - Failed
 */
export type StatusA93Enum = typeof StatusA93Enum[keyof typeof StatusA93Enum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusA93Enum = {
  pending: 'pending',
  running: 'running',
  success: 'success',
  failed: 'failed',
} as const;
