/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `pending` - Pending
* `running` - Running
* `success` - Success
* `failed` - Failed
 */
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusEnum = {
  pending: 'pending',
  running: 'running',
  success: 'success',
  failed: 'failed',
} as const;
