/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreLearningOutcome } from './coreLearningOutcome';

export interface StudentLearningOutcomeScore {
  readonly id: number;
  readonly student: string;
  readonly student_id: number;
  readonly learning_outcome: CoreLearningOutcome;
  /** @minimum 0 */
  score?: number;
}
