/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { CoreLearningOutcome } from './coreLearningOutcome';

/**
 * Serializer for StudentLearningOutcomeScore model.

Includes student details and nested learning outcome information.

Fields:
    id: Score record ID
    student: Student username (string representation)
    student_id: Student user ID
    learning_outcome: Nested LO object
    score: Calculated score (0-100)
 */
export interface StudentLearningOutcomeScore {
  readonly id: number;
  readonly student: string;
  readonly student_id: number;
  readonly learning_outcome: CoreLearningOutcome;
  /** @minimum 0 */
  score?: number;
}
