/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { ProgramOutcome } from './programOutcome';

/**
 * Serializer for StudentProgramOutcomeScore model.

Includes student, term, and nested program outcome information.

Fields:
    id: Score record ID
    student: Student username (string representation)
    term: Term name (string representation)
    program_outcome: Nested PO object
    score: Calculated aggregate score (0-100)
 */
export interface StudentProgramOutcomeScore {
  readonly id: number;
  readonly student: string;
  readonly term: string;
  readonly program_outcome: ProgramOutcome;
  /** @minimum 0 */
  score?: number;
}
