/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { ProgramOutcome } from './programOutcome';

export interface StudentProgramOutcomeScore {
  readonly id: number;
  readonly student: string;
  readonly term: string;
  readonly program_outcome: ProgramOutcome;
  /** @minimum 0 */
  score?: number;
}
