/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { Assessment } from './assessment';

export interface StudentGrade {
  readonly id: number;
  readonly student: string;
  readonly assessment: Assessment;
  /** @minimum 0 */
  score: number;
}
