/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface StudentProfile {
  readonly id: number;
  readonly user: User;
  user_id: number;
  /** @maxLength 20 */
  student_id: string;
  readonly enrollment_term: string;
  /** @nullable */
  enrollment_term_id?: number | null;
  readonly program: string;
  /** @nullable */
  program_id?: number | null;
}
