/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `course_recompute` - Course Recompute
 */
export type TaskTypeEnum = typeof TaskTypeEnum[keyof typeof TaskTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskTypeEnum = {
  course_recompute: 'course_recompute',
} as const;
