/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for Term (academic semester) model.

Fields:
    id: Term ID
    name: Term name (e.g., "Fall 2025")
    is_active: Whether this is the currently active term
 */
export interface Term {
  readonly id: number;
  /**
   * e.g., Fall 2025
   * @maxLength 100
   */
  name: string;
  is_active?: boolean;
}
