/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `progress` - progress
* `complete` - complete
 */
export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeEnum = {
  progress: 'progress',
  complete: 'complete',
} as const;
