/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for University model.

Handles serialization of university data with optional auto-generated code.

Fields:
    id: University ID
    name: University name
    code: University code (auto-generated if blank)
 */
export interface University {
  readonly id: number;
  /** @maxLength 255 */
  name: string;
  /** @maxLength 10 */
  code?: string;
}
