/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type V1CoreStudentPoScoresListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Filter PO scores by program ID
 */
program?: number;
/**
 * Filter PO scores by student ID
 */
student?: number;
/**
 * Filter PO scores by term ID
 */
term?: number;
};
