/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportAssignmentScoresValidateCreate200Checks } from './v1CoreFileImportAssignmentScoresValidateCreate200Checks';

export type V1CoreFileImportAssignmentScoresValidateCreate200 = {
  is_valid?: boolean;
  phase_reached?: string;
  checks?: V1CoreFileImportAssignmentScoresValidateCreate200Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
};
