/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportProgramOutcomesUploadRetrieve200Created } from './v1CoreFileImportProgramOutcomesUploadRetrieve200Created';
import type { V1CoreFileImportProgramOutcomesUploadRetrieve200Updated } from './v1CoreFileImportProgramOutcomesUploadRetrieve200Updated';

export type V1CoreFileImportProgramOutcomesUploadRetrieve200 = {
  created?: V1CoreFileImportProgramOutcomesUploadRetrieve200Created;
  updated?: V1CoreFileImportProgramOutcomesUploadRetrieve200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
