/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportProgramOutcomesUploadCreate200Created } from './v1CoreFileImportProgramOutcomesUploadCreate200Created';
import type { V1CoreFileImportProgramOutcomesUploadCreate200Updated } from './v1CoreFileImportProgramOutcomesUploadCreate200Updated';

export type V1CoreFileImportProgramOutcomesUploadCreate200 = {
  created?: V1CoreFileImportProgramOutcomesUploadCreate200Created;
  updated?: V1CoreFileImportProgramOutcomesUploadCreate200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
