/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportProgramTemplatesUploadRetrieve400Checks } from './v1CoreFileImportProgramTemplatesUploadRetrieve400Checks';
import type { V1CoreFileImportProgramTemplatesUploadRetrieve400Details } from './v1CoreFileImportProgramTemplatesUploadRetrieve400Details';

export type V1CoreFileImportProgramTemplatesUploadRetrieve400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: V1CoreFileImportProgramTemplatesUploadRetrieve400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: V1CoreFileImportProgramTemplatesUploadRetrieve400Details;
};
