/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportLearningOutcomesUploadCreate200Created } from './v1CoreFileImportLearningOutcomesUploadCreate200Created';
import type { V1CoreFileImportLearningOutcomesUploadCreate200Updated } from './v1CoreFileImportLearningOutcomesUploadCreate200Updated';

export type V1CoreFileImportLearningOutcomesUploadCreate200 = {
  created?: V1CoreFileImportLearningOutcomesUploadCreate200Created;
  updated?: V1CoreFileImportLearningOutcomesUploadCreate200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
