/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportProgramTemplatesUploadCreate200Created } from './v1CoreFileImportProgramTemplatesUploadCreate200Created';
import type { V1CoreFileImportProgramTemplatesUploadCreate200Updated } from './v1CoreFileImportProgramTemplatesUploadCreate200Updated';

export type V1CoreFileImportProgramTemplatesUploadCreate200 = {
  created?: V1CoreFileImportProgramTemplatesUploadCreate200Created;
  updated?: V1CoreFileImportProgramTemplatesUploadCreate200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
