/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type V1CoreFileImportProgramOutcomesUploadRetrieve400Details = { [key: string]: unknown };
