/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreEventsRetrieveFormat } from './v1CoreEventsRetrieveFormat';

export type V1CoreEventsRetrieveParams = {
format?: V1CoreEventsRetrieveFormat;
page?: number;
};
