/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportLearningOutcomesUploadRetrieve200Created } from './v1CoreFileImportLearningOutcomesUploadRetrieve200Created';
import type { V1CoreFileImportLearningOutcomesUploadRetrieve200Updated } from './v1CoreFileImportLearningOutcomesUploadRetrieve200Updated';

export type V1CoreFileImportLearningOutcomesUploadRetrieve200 = {
  created?: V1CoreFileImportLearningOutcomesUploadRetrieve200Created;
  updated?: V1CoreFileImportLearningOutcomesUploadRetrieve200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
