/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type V1CoreEventsRetrieveFormat = typeof V1CoreEventsRetrieveFormat[keyof typeof V1CoreEventsRetrieveFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const V1CoreEventsRetrieveFormat = {
  json: 'json',
  sse: 'sse',
} as const;
