/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportLearningOutcomesUploadCreate400Checks } from './v1CoreFileImportLearningOutcomesUploadCreate400Checks';
import type { V1CoreFileImportLearningOutcomesUploadCreate400Details } from './v1CoreFileImportLearningOutcomesUploadCreate400Details';

export type V1CoreFileImportLearningOutcomesUploadCreate400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: V1CoreFileImportLearningOutcomesUploadCreate400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: V1CoreFileImportLearningOutcomesUploadCreate400Details;
};
