/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportProgramOutcomesUploadRetrieve400Checks } from './v1CoreFileImportProgramOutcomesUploadRetrieve400Checks';
import type { V1CoreFileImportProgramOutcomesUploadRetrieve400Details } from './v1CoreFileImportProgramOutcomesUploadRetrieve400Details';

export type V1CoreFileImportProgramOutcomesUploadRetrieve400 = {
  error?: string;
  is_valid?: boolean;
  phase_reached?: string;
  checks?: V1CoreFileImportProgramOutcomesUploadRetrieve400Checks;
  errors?: string[];
  warnings?: string[];
  suggestions?: string[];
  details?: V1CoreFileImportProgramOutcomesUploadRetrieve400Details;
};
