/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { V1CoreFileImportProgramTemplatesUploadRetrieve200Created } from './v1CoreFileImportProgramTemplatesUploadRetrieve200Created';
import type { V1CoreFileImportProgramTemplatesUploadRetrieve200Updated } from './v1CoreFileImportProgramTemplatesUploadRetrieve200Updated';

export type V1CoreFileImportProgramTemplatesUploadRetrieve200 = {
  created?: V1CoreFileImportProgramTemplatesUploadRetrieve200Created;
  updated?: V1CoreFileImportProgramTemplatesUploadRetrieve200Updated;
  errors?: string[];
  skipped?: number;
  total_rows?: number;
};
