/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type V1CoreProgramsListParams = {
/**
 * Filter programs by degree level ID
 */
degree_level?: number;
/**
 * Filter programs by department ID
 */
department?: number;
/**
 * A page number within the paginated result set.
 */
page?: number;
};
