/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type V1EvaluationScoreRecomputeJobsListParams = {
/**
 * Filter jobs by course ID
 */
course?: number;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Filter jobs by status (pending, running, success, failed)
 */
status?: string;
};
