/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */

export type V1EvaluationGradesCourseAveragesRetrieveParams = {
/**
 * Get weighted average for specific course (class average or per-student)
 */
course?: number;
/**
 * When used with course parameter, returns individual student averages for grade distribution
 */
per_student?: boolean;
/**
 * Get weighted averages for specific student across all their courses
 */
student?: number;
};
