/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Student Evaluation System API
 * Outcome-based assessment system for academic programs
 * OpenAPI spec version: 1.0.0
 */
import type { StatusA93Enum } from './statusA93Enum';
import type { WeightSuggestionJobResult } from './weightSuggestionJobResult';

/**
 * Serializer for WeightSuggestionJob.
 */
export interface WeightSuggestionJob {
  readonly id: number;
  /** @nullable */
  course?: number | null;
  /** @nullable */
  triggered_by?: number | null;
  readonly status: StatusA93Enum;
  readonly celery_task_id: string;
  /** @nullable */
  readonly result: WeightSuggestionJobResult;
  readonly error: string;
  /** @nullable */
  readonly started_at: string | null;
  /** @nullable */
  readonly finished_at: string | null;
  readonly created_at: string;
  readonly updated_at: string;
}
